### ISSUE TITLE
Spi bus is just way too slow

### ISSUE THREAD

**Issue by SomeDoge** [juj/fbcp-ili9341#116]
- So, my SPI clock is extremely slow. I am getting artifacts (yellow lines) and extremely slow update rate even at 40 SPI bus clock divisor. Is it possible for soldering to be the problem? I am using 1.3inch 240x240 waveshare display . Here is the video (ignore sound in the background) https://youtu.be/J9P2_QtsPtc

**Comment by juj** [comment]
Using SPI bus clock divisor 40 is really slow indeed. Do the artifacts persists on faster clock speeds, or does the display crash altogether?

Not sure about the artifacts and the connection to soldering. It is a bit hard to say from the video, but if the artifact pixels always appear on individual one pixel tall lines, then it is definitely not a SPI bus soldering issue, as any signal issue on the SPI bus would not be able to "know" when one line ends and another starts. I would assume if there is a soldering connectivity issue, I'd expect the whole display to just not work, or show complete garbage for a sec and then crash.

If the artifacts always persist on the same scanline, then I would be suspicious of the display unit's ribbon connection from the controller to the display panel itself, since those have parallel traces and one bad trace can make a deterministically same kind of artifact.

It is also worth checking with Waveshare's own display driver to rule out a software issue.

**Comment by SomeDoge** [comment]
Okay, thanks. I will try to check the display.

**Comment by SomeDoge** [comment]
So, the ribbon cable seems fine. I uploaded another video detailing what's wrong

**Comment by juj** [comment]
The occasional lagging is most certainly due to low spi bus speed (sometimes the update will need to do a larger sub rectangle fill that takes much more bandwidth). If the bus does not hold up on faster settings, then you may be out of luck on that display :/

**Comment by SomeDoge** [comment]
Well, that's the problem. It was working absolutely fine just a week ago on 20 SPI divisor. The ribbon cable seems fine so idk what's actually the problem.

**Comment by SomeDoge** [comment]
And it's not just lagging. I don't think that the screen is supposed to refresh so that you can see the refresh going left to roght

**Comment by juj** [comment]
Closing out old issues.
