### ISSUE TITLE
It is possible use SP1?

### ISSUE THREAD

**Issue by naxeras** [juj/fbcp-ili9341#16]
Any possibility to add support for spi1 rather spi0?

Is for use in conjunction with gamecon:

https://github.com/RetroPie/RetroPie-Setup/wiki/GPIO-Modules#gamecon_gpio_rpi

Regards.

**Comment by juj** [comment]
Good question. Unfortunately the DMA controller on the Pi can only operate against SPI0, but not SPI1 (afaik), so if one would use the driver with SPI1, it would require disabling DMA, which would cause really high ~100% CPU usage. The FIFO length of the SPI1 controller is also much smaller than on SPI0, so it is possible that maximum frame rate would be slower as well. If you do still want to try to port to use SPI1, you should be able to do it following https://www.raspberrypi.org/app/uploads/2012/02/BCM2835-ARM-Peripherals.pdf documentation, because of the lack of DMA I don't think I will attempt that.
