### ISSUE TITLE
Waveshare 1.5inch RGB OLED Module

### ISSUE THREAD

**Issue by enes-oerdek** [juj/fbcp-ili9341#174]
Hey Guys,
first of all, great work! I worked on accomplishing the tasks this project does with c and fbcp, but I did not get good results. Then I accidentally found this project. The project name makes it hard to find this project though. I tried this out for the Waveshare 1.5inch RGB OLED Module (128x128), which can be found here:
https://www.waveshare.com/wiki/1.5inch_RGB_OLED_Module

It has the SSD1351 driver. By updating the height in ssd1351.cpp and ssd1351.h it worked like charms! I used these options:
`cmake -DSSD1351=ON -DGPIO_TFT_DATA_CONTROL=24 -DGPIO_TFT_RESET_PIN=25 -DSPI_BUS_CLOCK_DIVISOR=30  ..`

Also in config.h you need to uncomment to not have some frameshifting issues.
`#define UPDATE_FRAMES_WITHOUT_DIFFING`

No issues, I just wanted to tell you: Great job!

**Comment by juj** [comment]
I believe the root cause for the issue is something else, and using `#define UPDATE_FRAMES_WITHOUT_DIFFING` masks the issue by not having to send partial write windows. What the something else is, might be a bit trickier to find out. But if performance is good 60fps already with `UPDATE_FRAMES_WITHOUT_DIFFING` (on a 128x128 display it might), then may not be worth tweaking further.

**Comment by skittlesvampir** [comment]
Note for any future person who might encounter the same issues as me:

If you wire up the display to a Raspberry Pi as per the Waveshare Documentation, you need to configure with this command: `cmake -DSSD1351=ON -DGPIO_TFT_DATA_CONTROL=25 -DGPIO_TFT_RESET_PIN=27 -DSPI_BUS_CLOCK_DIVISOR=30 ..`

Please note that that the PIN numbers in this command are not the actual PIN numbers but the GPIO numbers. As you can see at https://pinout.xyz/, pin 13 is actually GPIO no. 27.
