### ISSUE TITLE
Statistics overlay

### ISSUE THREAD

**Issue by filthygurll** [juj/fbcp-ili9341#21]
I'm trying to disable overlay but it still shows up, I tried removing the whole // #define STATISTICS line from display.h but overlay still pops up

**Comment by juj** [comment]
Thanks for pointing this out. The control of the `STATISTICS` variable recently moved from config.h to CMake since it gets toggled so often that it is more convenient to not have to edit files to toggle it; but the documentation fell out of date. Updated the documentation in above commit to match the code now.

In particular, set `-DSTATISTICS=0` in CMake to remove the statistics overlay. You can build with `make VERBOSE=1` to see what options CMake is bringing in to the build, to see it transparently.
