### ISSUE TITLE
KeDei 3.5" spi driver?

### ISSUE THREAD

**Issue by gituser9991** [juj/fbcp-ili9341#27]
Hi there, have tried multiple cmake options but no luck. To save further wasted time can anyone confirm if it is possible to get the kedei 3.5" spi screen working with fbcp-ili9341?
cheers

**Comment by juj** [comment]
If this is the screen: http://imageshack.com/i/p77p1oydj, then it is possible that the display is a 3-wire SPI connection and not a 4-wire SPI one, since it looks like there is no Data/Control line used, at least there is no such pin present in the connector on that image.

If it is a 3-wire SPI display, then unfortunately it will not work with fbcp-ili9341. :(

**Comment by gituser9991** [comment]
Hi Juj, thanks for the fast reply...much appreciated. That looks like the sucker so you have saved me fruitless hours :o)  ...as  a famous bushranger said "Such is Life".  I can't expect too much for $6 I suppose!  The pinout says this:
24--GPIO7    --------> TP_CS
26--GPIO8    --------> LCD_CS
22--GPIO25  --------> TP_irq
23--GPIO11  --------> SPI_CLK
21--GPIO9    ---------> SPI_MISO
19--GPIO10 ---------> SPI_MOSI
5v           ---------> 5v
GND      ---------> GND

Cheers

**Comment by juj** [comment]
fbcp-ili9341 now gained 3-wire SPI support (no Data/Control line) in the above commit. That can be activated in CMake by setting `-DGPIO_TFT_DATA_CONTROL=-1` to tell the build system that there is no D/C pin to connect. The support is experimental, for example it currently does not support ILI9486 in 3-wire mode. Not sure what controller the KeDei display has, but there may be a chance that it could work, if it's like ILI9341 or ILI9486L in 3-wire mode.

See the above commit for updates to Readme.md for the docs.
