### ISSUE TITLE
Removing white screen at startup

### ISSUE THREAD

**Issue by milika** [juj/fbcp-ili9341#55]
Any way of starting with a black screen (waveshare3.5b) instead of white.
Im making a picture slideshow and its distracting when starting.
Thanks

**Comment by juj** [comment]
The default state for most displays I have met is that they power on the backlight and set all pixels to white. This occurs immediately when the 5V line (and backlight line, if that is separate/additional) is connected, without any software access. If you want to avoid this, it probably requires hardware solution where the 5V/backlight power line is not connected to the display until the Pi has fully booted and the display driver is ready to take over. Even with this kind of hardware mod, it is possible that there will still be a brief flash of white that occurs, since it will take about 500msecs to run the initialization sequence of a display to clear it to white. (you may be able to optimize it down to e.g. 200msec or 100msec, depending on the display in question)

The OLED displays I have tested all have their default power on state to be all pixels black, so they did not have this issue where a white flash would occur. Also the one ILI9486L display I had, had a special behavior compared to the rest that it inverted the color panel, so instead of starting backlight on+all pixels white at reset, it powered up with backlight on+all pixels black, so only backlight bleed against black image was visible. Not sure if all ILI9486L displays have that, or only that one design.

**Comment by milika** [comment]
Thank you for the answer, ill see about creating a controllable back-light with it being off as default...
Regards
