### ISSUE TITLE
Screen Tearing (Horizontal)

### ISSUE THREAD

**Issue by 32teeth** [juj/fbcp-ili9341#7]
After building an compiling, the screen runs awesome (generic ILI9341, pins 24,25)
Running RetroPie, on navigating through the menu i get slight horizontal tearing/artifcating

Playing games like Super Mario Word, tearing is too severe and disrupts gameplay

Hardware:
Raspberry Pi Zero W

Suggestions?

**Comment by juj** [comment]
Screen tearing is caused by lack of vsync signal on the SPI protocol. You can adjust https://github.com/juj/fbcp-ili9341/blob/master/config.h#L117 to trade straight line tearing artifact to diagonal tearing, whichever looks more subjectively pleasing. By default Pi Zero W uses diagonal tearing (https://github.com/juj/fbcp-ili9341/blob/master/config.h#L116) since the straight line tearing toggle consumes some extra cpu.

The only real solution is to switch to a DPI display, or to a good HDMI display. (The cheap HDMI displays such as KeDei 3.5" also have tearing, they disregard vsync)
